// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.mahaattie.com
// Generated: 2026-06-24T09:58:43.923Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary';
export type ColorHex  = '#1d2944' | '#e4e8ec' | '#000000' | '#8492ae' | '#ffffff' | '#c1c1c1';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'salmanazar-lk7x9s' | 'aktiv-grotesk' | 'ibm-plex-mono';
export type FontSizeToken   = never;
export type FontWeightToken = '600' | '400' | '700';

export type SpacingToken = '1px' | '32px' | '36px' | '64px' | '71px' | '84px' | '92px';

export type RadiusToken = '2px' | '50px' | '150px' | '300px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '600ms' | '1500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
